### PR TITLE
Nftfrontend2

### PR DESCRIPTION
**Pull request by thedatadudech**
Hi I wanted to push my frontend, but encountered some difficulties, so I changed also the random function and also now in BuyTicket I took out the missing ticket account that I was still depending on. For me it worked.

Please consider if you want check frontend also yourself you have to deploy the program and use the program ID

in anchor.toml
then for frontend it needs to be changed in  lottery-exports.ts
export const LOTTERY_PROGRAM_ID = new PublicKey(
  '8b8fSgX4sqiW5amc6AD9sgj8NzS94N8V71ipJTPK9RPv'
);

### CODE REVIEW

**Review by luca-nik — APPROVED** [review]
Great job!

**Comment by luca-nik** [comment]
Together with @helloalex-x , we fixed the problem with the Ticket account creation, and we also included the NFT minting when the ticket is bought. I will push the modifications directly on this branch

**Comment by thedatadudech** [comment]
@0xAlvarenga  is it ok to merge the PR ?

**Comment by 0xAlvarenga** [comment]
Sounds good for me, go for it!

-------- Original Message --------

**Pull request merged**
